cc_library(
	name = 'heavy-path-decomposition',
	hdrs = ['heavy_path_decomposition.hh'],
	visibility = ['//visibility:public'],
)

cc_library(
	name ='weight-balanced-tree',
	hdrs = ['weight_balanced_tree.hh'],
	visibility = ['//visibility:public'],
)
